name: main

on:
  workflow_dispatch:
  
  schedule:
    # UTC 时间
     - cron: "5 */6 * * *"    
  watch: 
      types: started

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.7'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests
        pip install user_agent
    - name: Run
      run: |
        python fee.py
     
